### ISSUE TITLE
Lastest version is not published in rubygems!

### ISSUE THREAD

**Issue by fabioperrella** [gabrielgiordano/tracer#1]
Whats up @gabrielgiordano !!

I've tried to test this gem, but I found the latest version is not published in rubygems.

Could you publish it pls?

Last week I read about the gem https://github.com/zeisler/visualize_ruby and I remembered you and Ricardo were doing something like this and I would like to try it!

**Comment by gabrielgiordano** [comment]
Whats up @fabioperrella! Great to hear from you!

The gem is a little bit rough in the edges and while we were testing we noticed that the performance was not that good. After a while, we found another gem that has a good performance but it's missing some visualization feature and does not grab all the information we wanted at the time. It's this one https://github.com/Shopify/rotoscope . Maybe rotoscope will be a fit for your needs.

I don't know if I can work in this gem right now, but I can try to help with whatever I can. 
The visualization we were doing was basically building up a tree based on the output of the trace and then recreating the execution path. The code is in this [folder](https://github.com/gabrielgiordano/tracer/tree/master/visualization), but please note that is missing a lot of features, and the path to the source code, if I recall correctly, still is hardcoded. The code that builds the tree is located [here](https://github.com/gabrielgiordano/tracer/blob/master/visualization/js/tracer.js) and the tree implementation is [here](https://github.com/gabrielgiordano/tracer/blob/master/visualization/js/execution_tree.js). And we were using https://prismjs.com/ to show the code in the visualization. Maybe this code could be useful for you if you want to build a visualization with rotoscope.

Please let me know if I can help with something else :wink: . And send some hugs to the guys :smile:

**Comment by fabioperrella** [comment]
Thank you @gabrielgiordano ! I will try the gem `rotoscope` and if it does not fit what I am searching, I will try to contribute here.

Send hugs to the guys too!!
